package com.example.customerservice.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.example.customerservice.config.ConversationMemoryProperties;
import com.example.customerservice.model.SessionContextWindow;
import com.example.customerservice.model.SessionRole;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ConversationMemoryServiceTest {

    @Test
    void contextWindowUsesSummaryPlusRecentVerbatimTurns() {
        ConversationMemoryService service =
                new ConversationMemoryService(new ConversationMemoryProperties(true, 6, 1200, 2, 400));

        service.appendExchange("session-1", "question 1 about refunds", "answer 1");
        service.appendExchange("session-1", "question 2 about refund status", "answer 2");
        service.appendExchange("session-1", "question 3 about shipping", "answer 3");
        service.appendExchange("session-1", "question 4 about delivery time", "answer 4");

        SessionContextWindow contextWindow = service.getContextWindow("session-1");

        assertEquals(8, contextWindow.recentMessages().size());
        assertEquals(SessionRole.USER, contextWindow.recentMessages().get(0).role());
        assertTrue(contextWindow.summary().isPresent());
        assertTrue(contextWindow.summary().orElseThrow().summary().contains("question 1"));
        assertEquals(2, contextWindow.promptTurns().size());
        assertEquals("question 3 about shipping", contextWindow.promptTurns().get(0).userMessage());
        assertEquals("question 4 about delivery time", contextWindow.latestTurn().orElseThrow().userMessage());
    }

    @Test
    void rolledSummaryPreservesTurnsEvictedFromRecentWindow() {
        ConversationMemoryService service =
                new ConversationMemoryService(new ConversationMemoryProperties(true, 3, 1200, 2, 400));

        service.appendExchange("session-2", "question 1 about damaged order", "answer 1");
        service.appendExchange("session-2", "question 2 about compensation", "answer 2");
        service.appendExchange("session-2", "question 3 about shipping", "answer 3");
        service.appendExchange("session-2", "question 4 about escalation", "answer 4");

        SessionContextWindow contextWindow = service.getContextWindow("session-2");

        assertEquals(3, contextWindow.recentTurns().size());
        assertEquals(2, contextWindow.promptTurns().size());
        assertTrue(contextWindow.summary().isPresent());
        assertTrue(contextWindow.summary().orElseThrow().summary().contains("question 1 about damaged order"));
    }

    @Test
    void databaseBackedMemorySurvivesServiceRecreation() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        createConversationMemorySchema(jdbcTemplate);

        ConversationMemoryProperties properties = new ConversationMemoryProperties(true, 6, 1200, 2, 400);
        ConversationMemoryService firstService = new ConversationMemoryService(
                properties,
                jdbcTemplate,
                new DataSourceTransactionManager(dataSource)
        );
        firstService.appendExchange("session-db", "question about persistent memory", "answer from database");

        ConversationMemoryService secondService = new ConversationMemoryService(
                properties,
                jdbcTemplate,
                new DataSourceTransactionManager(dataSource)
        );
        SessionContextWindow contextWindow = secondService.getContextWindow("session-db");

        assertEquals(1, contextWindow.recentTurns().size());
        assertEquals("question about persistent memory", contextWindow.latestTurn().orElseThrow().userMessage());
        assertEquals("answer from database", contextWindow.latestTurn().orElseThrow().assistantMessage());
    }

    private void createConversationMemorySchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                create table conversation_thread (
                  session_id varchar(128) primary key,
                  summary_topic varchar(512),
                  summary_text clob,
                  summary_version int not null default 0,
                  created_at timestamp(6) not null default current_timestamp,
                  updated_at timestamp(6) not null default current_timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table conversation_message (
                  id bigint generated by default as identity primary key,
                  message_id varchar(36) not null unique,
                  session_id varchar(128) not null,
                  turn_no int not null,
                  role varchar(16) not null,
                  source_type varchar(32) not null default 'CHAT',
                  content clob not null,
                  created_at timestamp(6) not null default current_timestamp,
                  constraint fk_conversation_message_thread
                    foreign key (session_id) references conversation_thread(session_id)
                    on delete cascade
                )
                """);
    }
}
